version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  producer:
    build:
      context: ./producer  # Ruta al directorio del productor
    depends_on:
      - kafka
    networks:
      - kafka-net

  consumer:
    build:
      context: ./consumer  # Ruta al directorio del consumidor
    depends_on:
      - kafka
    networks:
      - kafka-net

networks:
  kafka-net:
